baseurl = "https://bearlyapodcast.net/"
languageCode = "en-gb"
title = "bearly a podcast"
theme = "castanet"
googleAnalytics = ""
themesdir = "themes"
paginate = "9"
buildFuture = true


[permalinks]
	page = "/:filename/"
	about = "/:filename/"
	episode = "/:filename/"


# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# The menus are sorted based upon their identifier
#[[Menu.Main]]
#    name = "About"
#    identifier = "about"
#    url = "/about"

[[Menu.Main]]
    name = "Contact"
    identifier = "contact"
    url = "/contact"

[[Menu.Main]]
    name = "Hosts"
    identifier = "hosts"
    url = "/host"

[[Menu.Main]]
    name = "Guests"
    identifier = "guests"
    url = "/guest"

[[Menu.Main]]
    name = "Upcoming Episodes"
    identifier = "upcoming"
    url = "/upcoming"

[[Menu.Main]]
    name = "Resources"
    identifier = "resources"
    url = "#!"

[[Menu.Main]]
    name = "Attributions"
    identifier = "attr"
    url = "/attributions"
    parent = "resources"
#[[Menu.Main]]
#    name = "Podcasts"
#    identifier = "podcasts"
#    url = "/books"
#    parent = "resources"

[params]
mainSections = ["episode"]
site_theme = "grey"
# site_layout = "grid"
site_layout = "row"
enable_jumbo = "true"
# enable_jumbo = "false"
# truncate = "100"
about_logo = "https://www.bearlyapodcast.net/img/genericCover(2).png"
copyright_notice = "bearly a podcast! by [Matthew Harazim](https://www.matthewharazim.co.uk) is licensed under [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/?ref=chooser-v1) [![](/img/valid-rss-rogers.png)](https://validator.w3.org/feed/check.cgi?url=https%3A//bearlyapodcast.net/episode/index.xml)"
itunes_subscribe = "https://podcasts.apple.com/us/podcast/arrested-devops/id773888088?ign-mpt=uo%3D4&mt=2"
android_subscribe = "https://subscribeonandroid.com/media.rss.com/bearlyapodcast/feed.xml"
spotify_subscribe = "https://open.spotify.com/show/3QxxEMc4L3CuUGXmx9Ynhv"
#google_play_subscribe = "https://goo.gl/app/playmusic?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&link=https://play.google.com/music/m/Ihj4yege3lfmp3vs5yoopgxijpi?t%3DArrested_DevOps"
stitcher_subscribe = "https://www.stitcher.com/podcast/bearly-a-podcast"
soundcloud_subscribe = "https://feeds.soundcloud.com/users/soundcloud:users:939425785/sounds.rss"
pocketcasts_subscribe = "https://pca.st/ccgp5b5d"
#mailchimp_subscribe = "//arresteddevops.us3.list-manage.com/subscribe/post?u=5e4cbcac996bb9df25f970a89&amp;id=154fa76bcc"
#rss_subscribe = "http://feed.com/myfeed" #only set this if you don't want to use the built-in feed
description = "![bearlyAPodcast](img/hugoHeader.png) bearly a podcast! is a audio blog/podcast about Matt, a 25 y/o wannabe sound engineer, with lots of knowledge and no experience. Each week, Matt tackles a new and exciting topic; sometimes trying to learn things, sometimes trying to teach. If you like nerdy things, pop culture and seeing if one man can crack the audio industry then this podcast is for you! Follow Matt as he spirals out of control regarding the weeks' topic - sometimes even with a guest. Topics range from [CBD](https://www.bearlyapodcast.net/ep01), to [homelabs](https://www.bearlyapodcast.net/ep02) and everything in between. Publishing cycle has yet to be defined, however, **Mondays** seem very likely!"
media_prefix = "https://www.bearlyapodcast.net/"
#disqusShortname = ""
  [params.feed]
    copyright = "Copyright 2020 Matt Harazim" #do not use markdown in this field; it is used in the feed
#    itunes_subtitle = "Magic, Mayhem and Madness" #no markdown or HTML
    itunes_author = "Matthew Harazim" #no markdown or HTML
    itunes_summary = "Matt thought as an unemployed audio creative, having a podcast on his portfolio might get him a job. Then he thought, what the heck? Join him on a weekly tangent on a random topic, from CBD to Homelabs, and everything in between. Sometimes even with a guest!" # Limited to 4000 characters or less, plain text, no HTML
    itunes_owner_name = "Matthew Harazim"
    itunes_owner_email = "matthewharazim@vivaldi.net" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on Apple Podcasts. It will not be publicly displayed on Apple Podcasts.
    itunes_image = "https://www.bearlyapodcast.net/img/genericCover(2).png" #fqdn to the image art for your podcast
    itunes_top_category = "Leisure"
    itunes_first_sub_category = "Hobbies"
    itunes_second_sub_category = "Games"
    language = "en-gb"

  [params.realfavicongenerator] # https://realfavicongenerator.net/
    mask_icon_color="#5bbad5"
    msapplication_tilecolor="#2b5797"
    theme_color="#ffffff"

  [params.podlove] # https://subscribe-button.podlove.org
    subscribe_title = "bearly a podcast!"              # fallback: site title from above
    subscribe_subtitle = ""           # fallback: ""
    subscribe_description = ""        # fallback: ""
    subscribe_cover = "img/genericCover(2).png"  # fallback: "/img/logo.jpg"
    subscribe_color = "#585e6c"       # fallback: ""
    subscribe_size = "medium"         # options: small, medium, big
    subscribe_format = "cover"    # options: rectangle, square, cover
    subscribe_style = "filled"        # options: filled, outline, frameless
    subscribe_language = "en"         # options: nl (dutch), en (english), eo (esperanto), de (german), fi (finnish), fr (french), ja (french)
    subscribe_feed_type = "audio"     # options: audio, video
    subscribe_feed_format = "mp3"     # options: mp3, aac, ogg, opus

  [params.social]
 #   github = "arresteddevops"
 #   gitlab = "mattstratton"
 #   facebook = "Arresteddevops"
 #   facebook_admin = ["500557137","1234"] # This needs to be one or more page admins to get domain insights
    twitter = "bearly_matt"
#    twitter_domain = "arresteddevops.com" # This domain shows in twitter cards as "View on `twitter_domain`"
#    googleplus = "ArrestedDevOps"
#    pinterest = "nozzleio"
    instagram = "matthewharazim"
#    youtube = "arresteddevops"
#    linkedin = "mattstratton"
    twitch = "PunckRockTurtle"

  [params.authors]
    [params.authors.Matt]
      name	= "Matt Harazim"
      thumbnail = "img/host/matt.jpeg"
      bio = "Matt is an unemployed sound designer and audio engineer, who is currently employed in the retail sector. He's known for rambling and making a complete fool of himself, all the while enjoying RPGs (Blades in the Dark, D&D 5e, Heart the City Beneath, and Symbaroum), tinkering on his homelab, and forcing two cats to love him"
      [params.authors.Matt.social]
        github = "bearlymatt"
#        facebook = "matt.stratton"
        twitter = "bearly_matt"
#        linkedin = "mattstratton"
        homepage = "https://www.matthewharazim.co.uk"
#        pinterest = "mattstratton"
        instagram = "matthewharazim"
#        youtube = "mattstratton"
        twitch = "PunckRockTurtle"
#    [params.authors.Trevor]
#			name = "Trevor Hess"
#			thumbnail = "https://www.arresteddevops.com/img/trevor.png"
#			bio = ""
#				[params.authors.Trevor.social]
#					twitter = "trevorghess"
 #   [params.authors.Bridget]
  #    name = "Bridget Kromhout"
#      thumbnail = "https://www.arresteddevops.com/img/Bridget.png"
#      bio = ""
#      [params.authors.Bridget.social]
#        twitter = "bridgetkromhout"

    [params.links]
      [params.links.ado]
        name = "Arrested DevOps"
        url = "https://www.arresteddevops.com"
      [params.links.ffs]
        name = "Food Fight Show"
        url = "https://foodfightshow.org"
      [params.links.sdt]
        name = "Software Defined Talk"
        url = "https://cote.io/podcasts/sdt/"
